import type { BiomeId, Choice, Enemy, Item, Quest, StoryEvent } from "./data";

export const ROMANS = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"];

const gear = (
  id: string,
  name: string,
  slot: Item["slot"],
  act: number,
  description: string,
  bonuses: Partial<Item>,
): Item => ({
  id,
  name,
  slot,
  act,
  description,
  rarity: act >= 7 ? "Legendary" : "Rare",
  price: 90 + act * 65,
  icon: slot === "weapon" ? "sword" : slot === "armor" ? "armor" : "charm",
  ...bonuses,
});
export const EXTRA_ITEMS: Item[] = [
  gear(
    "saltglass-rapier",
    "Saltglass Rapier",
    "weapon",
    4,
    "An admiral's dueling blade. Salt crystals repair its edge after every tide.",
    { attack: 22, crit: 8 },
  ),
  gear(
    "copper-harpoon",
    "Widow's Harpoon",
    "weapon",
    4,
    "Lysa forged it to bring her husband's boat home. It returned without him.",
    { attack: 25 },
  ),
  gear(
    "index-blade",
    "The Index Blade",
    "weapon",
    5,
    "Each rune names a book the fire failed to erase. The steel remembers its readers.",
    { attack: 28, energy: 12 },
  ),
  gear(
    "cinder-mace",
    "Cinder Judgment",
    "weapon",
    5,
    "The court's final verdict was hammered into this mace. No one signed it.",
    { attack: 32, hp: 12 },
  ),
  gear(
    "mirror-wand",
    "Shard of Another Sky",
    "weapon",
    6,
    "The reflection at its tip arrives a heartbeat before your hand moves.",
    { attack: 33, energy: 18 },
  ),
  gear(
    "eclipse-scythe",
    "Eclipse Reaper",
    "weapon",
    6,
    "A crescent of star iron cuts the threads that tie a shadow to its owner.",
    { attack: 36, crit: 15 },
  ),
  gear(
    "rootbone-spear",
    "Rootbone Promise",
    "weapon",
    7,
    "Grown around a pearl containing one honest memory. It will never bend.",
    { attack: 40, hp: 20 },
  ),
  gear(
    "abyss-trident",
    "The Undertow",
    "weapon",
    7,
    "Three obsidian teeth taken from a tide that once swallowed a kingdom.",
    { attack: 43, crit: 10 },
  ),
  gear(
    "dawn-sword",
    "After the Last Night",
    "weapon",
    8,
    "Its halo is broken so the light can leave. A weapon made for an ending.",
    { attack: 48, energy: 15 },
  ),
  gear(
    "salt-coat",
    "Saltkeeper's Coat",
    "armor",
    4,
    "Heavy canvas remembers the warmth of every sailor who borrowed it.",
    { defense: 13, hp: 25 },
  ),
  gear(
    "diver-cuirass",
    "Depthwarden Cuirass",
    "armor",
    4,
    "A sealed bronze shell. The tide can take your breath only if you lend it.",
    { defense: 16, hp: 32 },
  ),
  gear(
    "archive-robe",
    "Unwritten Robes",
    "armor",
    5,
    "Blank margins cover the opaque hood. Some truths need room to change.",
    { defense: 15, energy: 20 },
  ),
  gear(
    "cinder-plate",
    "Last Court Brigandine",
    "armor",
    5,
    "Ember-red plates bear the marks of a trial conducted after everyone died.",
    { defense: 19, hp: 40 },
  ),
  gear(
    "mirror-plate",
    "Regent's Reflection",
    "armor",
    6,
    "Black glass hides the wearer completely. It reflects the blow, never the face.",
    { defense: 21, crit: 8 },
  ),
  gear(
    "eclipse-mantle",
    "Midnight Scale Mantle",
    "armor",
    6,
    "A hood stitched from the shadows of stars. Its seams are almost weightless.",
    { defense: 20, energy: 24 },
  ),
  gear(
    "root-armor",
    "The Living Shelter",
    "armor",
    7,
    "The roots hold you as they once held the shore. They ask only to be remembered.",
    { defense: 24, hp: 55 },
  ),
  gear(
    "abyss-shell",
    "Leviathan's Mercy",
    "armor",
    7,
    "A shell surrendered rather than stolen. Its owner still follows the tides.",
    { defense: 27, hp: 48 },
  ),
  gear(
    "dawn-plate",
    "Custodian's Dawnplate",
    "armor",
    8,
    "The helm has no eye slits. The light inside has learned to see another way.",
    { defense: 31, hp: 65 },
  ),
  gear(
    "white-ash",
    "Mantle of the Unburnt",
    "armor",
    8,
    "White cloth survived the first fire. Gold clasps keep its long history together.",
    { defense: 25, energy: 32, hp: 35 },
  ),
  gear(
    "salt-compass",
    "The Returning Compass",
    "charm",
    4,
    "It points toward whoever is waiting for you, even beneath the ocean.",
    { hp: 24, crit: 9 },
  ),
  gear(
    "tide-bell",
    "Little Tide Bell",
    "charm",
    4,
    "Its silent movement steadies a pulse. The dead hear it more clearly.",
    { energy: 18, hp: 15 },
  ),
  gear(
    "oath-scroll",
    "The Unsealed Oath",
    "charm",
    5,
    "A promise kept in a silver tube. There is still space beneath the signature.",
    { hp: 32, energy: 12 },
  ),
  gear(
    "cinder-crown",
    "Signet of No King",
    "charm",
    5,
    "The crown's smallest fragment refuses to recognize a throne.",
    { crit: 18, hp: 20 },
  ),
  gear(
    "mirror-pendant",
    "Witness in Black Glass",
    "charm",
    6,
    "Someone inside the shard blinks whenever you tell the truth.",
    { energy: 25, crit: 10 },
  ),
  gear(
    "memory-pearl",
    "One Honest Memory",
    "charm",
    6,
    "A winter kitchen. Bread cooling. A hand held without asking anything.",
    { hp: 45, energy: 15 },
  ),
  gear(
    "brass-orrery",
    "The Smallest Sky",
    "charm",
    6,
    "The planets turn around an empty center. You can finally see where the sun was.",
    { crit: 22, energy: 18 },
  ),
  gear(
    "root-heart",
    "Heart of the Shore",
    "charm",
    7,
    "The sea grows roots around the memories it cannot bear to lose.",
    { hp: 60, energy: 18 },
  ),
  gear(
    "abyss-amulet",
    "The Quiet Below",
    "charm",
    7,
    "Hold the shell to your ear. For once, nothing is asking to be saved.",
    { crit: 24, hp: 30 },
  ),
  gear(
    "dawn-key",
    "Key to Tomorrow",
    "charm",
    8,
    "It fits no lock. The Custodian insists that this is the point.",
    { hp: 55, energy: 35 },
  ),
  gear(
    "joined-rings",
    "A Promise Shared",
    "charm",
    8,
    "Two rings, neither closed. A vow is strongest when it leaves a way out.",
    { hp: 70, energy: 24, crit: 15 },
  ),
];

export const EXTRA_BIOMES = [
  {
    id: "saltreach" as BiomeId,
    name: "The Saltreach",
    subtitle: "A harbor below the tide",
    description:
      "The sea arrived without water. Now the harbor's bells toll beneath streets paved with salt, and the drowned demand a debt the living do not remember.",
    level: 8,
    art: 4,
    boss: "admiral",
    quest: "admiral",
    unlock: "keeper-secret",
  },
  {
    id: "archive" as BiomeId,
    name: "The Cinder Archive",
    subtitle: "Where the fire kept its witnesses",
    description:
      "Books burn without becoming ash. Three authors signed the decree that ended daylight. Someone has spent thirty years erasing the third signature.",
    level: 11,
    art: 5,
    boss: "librarian",
    quest: "librarian",
    unlock: "dead-letter",
  },
  {
    id: "observatory" as BiomeId,
    name: "The Mirror Observatory",
    subtitle: "A sky built from stolen stars",
    description:
      "The mirrors reflect a world that never fell. The Regent offers that world to anyone willing to leave the real one behind.",
    level: 14,
    art: 6,
    boss: "regent",
    quest: "regent",
    unlock: "third-author",
  },
  {
    id: "rootsea" as BiomeId,
    name: "The Rootsea",
    subtitle: "Every forgotten shore",
    description:
      "An ocean under the forest carries the memories daylight would erase. Your lantern grows heavier here. Something inside it wants to go home.",
    level: 17,
    art: 7,
    boss: "leviathan",
    quest: "leviathan",
    unlock: "reflection",
  },
  {
    id: "engine" as BiomeId,
    name: "The Dawn Engine",
    subtitle: "What comes after the last night",
    description:
      "A machine large enough to turn a world waits behind three broken seals. It can restore the sun. It cannot decide who deserves to survive the morning.",
    level: 20,
    art: 8,
    boss: "custodian",
    quest: "custodian",
    unlock: "borrowed-heart",
  },
];

const foe = (
  id: string,
  name: string,
  title: string,
  art: number,
  hp: number,
  attack: number,
  defense: number,
  description: string,
  intent: string[],
  boss = false,
): Enemy => ({
  id,
  name,
  title,
  art,
  hp,
  attack,
  defense,
  description,
  intent,
  boss,
  xp: boss ? Math.round(hp * 1.3) : Math.round(hp * 0.7),
  gold: boss ? Math.round(hp * 0.6) : Math.round(hp * 0.3),
});
export const EXTRA_ENEMIES = [
  foe(
    "admiral",
    "The Drowned Admiral",
    "Collector of the living's debts",
    6,
    255,
    28,
    11,
    "The sealed helmet holds a voice, a tide, and the names of the crew he could not save.",
    ["Harpoon sweep", "The tide withdraws", "Deadwater surge"],
    true,
  ),
  foe(
    "librarian",
    "The Ash Librarian",
    "Guardian of the third signature",
    7,
    340,
    33,
    13,
    "Her opaque veil is made from the pages she refused to burn. The missing signature is stitched inside it.",
    ["Paperblade", "Turning the last page", "Cinder verdict"],
    true,
  ),
  foe(
    "regent",
    "The Mirror Regent",
    "A future without a past",
    8,
    435,
    39,
    16,
    "The black helm reflects an unbroken kingdom. Its ruler has forgotten which side of the glass he occupies.",
    ["Glass lance", "Preparing a reflection", "Shattered sky"],
    true,
  ),
  foe(
    "leviathan",
    "The Rootsea Leviathan",
    "The shore that remembers",
    9,
    550,
    45,
    18,
    "Every luminous root along its spine holds a town the sun has already forgotten.",
    ["Undertow", "A long breath below", "The ocean rises"],
    true,
  ),
  foe(
    "custodian",
    "The Dawn Custodian",
    "The last unanswered question",
    10,
    700,
    52,
    21,
    "The enclosed golden armor contains no ruler. It is a promise waiting to discover whether you understand it.",
    ["Ring of embers", "Opening the dawn gate", "First morning"],
    true,
  ),
  foe(
    "salt-marauder",
    "Saltbound Marauder",
    "A debt with a blade",
    11,
    105,
    22,
    7,
    "The diver's mask has rusted shut. Coins still fall from its gloves.",
    ["Hooking strike", "Drawing a cold breath", "Salt rake"],
  ),
  foe(
    "cinder-moth",
    "Cinder Moth",
    "A page that learned to hunt",
    12,
    145,
    27,
    8,
    "Its wings contain a sentence that can no longer be safely read.",
    ["Ember dust", "Wings folding", "Burning swarm"],
  ),
  foe(
    "glass-watcher",
    "Glass Watcher",
    "An answer without a question",
    13,
    190,
    32,
    12,
    "There is no face under the crystal armor. Only the reflection of whoever struck first.",
    ["Shard cut", "Mirror ward", "Prismatic fracture"],
  ),
  foe(
    "sea-oracle",
    "Rootsea Oracle",
    "Listener to the lost shores",
    14,
    240,
    37,
    13,
    "The pearl beneath the opaque wrappings contains a voice older than the sea.",
    ["Pearl pulse", "Remembering warmth", "Drowned remembrance"],
  ),
];

const c = (
  label: string,
  hint: string,
  outcome: string,
  extras: Partial<Choice> = {},
): Choice => ({ label, hint, outcome, ...extras });
const mq = (
  id: string,
  name: string,
  act: number,
  biome: BiomeId,
  requires: string | undefined,
  description: string,
  objective: string,
  objectiveKey: string,
  reward?: string,
): Quest => ({
  id,
  name,
  type: "Main quest",
  chapter: `Act ${ROMANS[act - 1]} · ${["The Drowned Witness", "A Name of Your Own", "The False Dawn", "Debts Beneath the Tide", "The Third Signature", "A Sky of Mirrors", "What the Sea Keeps", "The Shape of Morning"][act - 1]}`,
  biome,
  requires,
  description,
  objective,
  objectiveKey,
  goal: 1,
  gold: 40 + act * 28,
  xp: 50 + act * 40,
  reward,
});
const decision = (q: Quest, text: string, choices: Choice[]): Quest => ({
  ...q,
  scene: { text, choices },
});

export const CAMPAIGN_QUESTS: Quest[] = [
  mq(
    "bell",
    "For Whom the Bell Tolls",
    1,
    "catacombs",
    undefined,
    "Maren gives you a list of the drowned. The last entry is dated tomorrow. Beneath the sanctuary, a bell rings once for every name still on the page.",
    "Silence the Bell Warden",
    "boss:warden",
    "bellplate",
  ),
  mq(
    "drowned-ledger",
    "The Name Dated Tomorrow",
    1,
    "catacombs",
    "bell",
    "The Warden was counting prisoners, not graves. Find his ledger before Maren's guards seal the lower stairs. Your own handwriting appears in the margins.",
    "Recover the Warden's ledger",
    "event:ledger",
    "cinder-ring",
  ),
  decision(
    mq(
      "testimony",
      "What Maren Withheld",
      1,
      "catacombs",
      "drowned-ledger",
      "Maren agrees to speak in the shrine after sunset. Bring the ledger. Listen before deciding whose version of the past the town will hear.",
      "Hear Maren's testimony",
      "decision:testimony",
    ),
    "Maren removes a glove, not her mask. The hand beneath it belongs to a woman much younger than her voice.\n\n“The darkness was a wall,” she says. “Outside it, the sun had begun burning people from history. We sheltered whoever we could remember.”\n\nThe ledger records those she could not save. Your name is dated tomorrow because the wall is failing. She asks you to hide the ledger until she can prepare the town. Through the shrine door, you hear children practicing names they may soon lose.",
    [
      c(
        "Let the town hear the truth",
        "+2 trust · witnesses will help later",
        "Maren stands beside you as the ledger is read. No one cheers. A baker offers blankets; a guard sets down his spear. Fear becomes work that can be shared.",
        { reputation: 2, flag: { key: "ledger", value: "public" } },
      ),
      c(
        "Give Maren time",
        "+35 gold · preserve the council's support",
        "The ledger returns to Maren's locked drawer. She sends supplies to the lower streets before dawn. It is a useful kindness built on another silence.",
        { gold: 35, flag: { key: "ledger", value: "sealed" } },
      ),
    ],
  ),
  mq(
    "moths",
    "The Names We Lost",
    2,
    "thornwild",
    "testimony",
    "A child at the gate answers to every name but their own. The moths are not stealing names; they are carrying them away from something that hunts by memory.",
    "Confront the Moth Sovereign",
    "boss:sovereign",
    "thorn-dagger",
  ),
  mq(
    "borrowed-names",
    "A Name Worth Keeping",
    2,
    "thornwild",
    "moths",
    "The Sovereign left one cocoon unopened. A girl inside it remembers two childhoods. Find her before the council decides which childhood is allowed to be real.",
    "Find the girl in the unopened cocoon",
    "event:cocoon",
    "moth-charm",
  ),
  decision(
    mq(
      "changeling",
      "The Child at the Door",
      2,
      "thornwild",
      "borrowed-names",
      "The girl asks for a name of her own. Her other memories belong to someone the town buried thirty years ago.",
      "Choose the child's place in Vesper's Rest",
      "decision:changeling",
    ),
    "The child waits outside the tavern with a moth cupped between both hands. She knows the old baker's wedding song, and the password to a house that no longer stands. She also knows how to laugh at a joke she has never heard before.\n\nCaptain Oren calls her an imitation. The baker calls her his daughter. Neither asks what she wants.\n\n“I remember being someone else,” she tells you through her cloth mask. “But I am the one standing here.” Her moth opens its wings. There is no borrowed name written on them.",
    [
      c(
        "Give her a new name: Nera",
        "+3 trust · Nera becomes an ally",
        "Nera chooses the room above the tavern. The baker leaves breakfast outside her door and learns, slowly, not to call her by the old name.",
        { reputation: 3, flag: { key: "nera", value: "free" } },
      ),
      c(
        "Ask the shrine to protect her",
        "+20 resolve · keep her out of danger",
        "The shrine offers shelter and a new cloth veil. Nera thanks you, then asks whether protection always requires a locked door. You leave the key with her.",
        { resolve: 20, flag: { key: "nera", value: "sheltered" } },
      ),
    ],
  ),
  mq(
    "flame",
    "The Last Light",
    3,
    "spire",
    "changeling",
    "The Spire's flame powers the sheltering wall. Its keeper stopped sending fuel years ago. Follow the ancient stairs and discover what has been burning in its place.",
    "Reach the Unlit Heart",
    "boss:heart",
    "first-light",
  ),
  mq(
    "false-dawn",
    "A Sunrise Made of Names",
    3,
    "spire",
    "flame",
    "The Heart was an engine, not a god. A broken lens shows the fuel ledger. Restore its focus long enough to read the entries erased from Maren's copy.",
    "Align the broken dawn lens",
    "event:dawn-lens",
    "oracle-staff",
  ),
  decision(
    mq(
      "keeper-secret",
      "The Passenger in the Lantern",
      3,
      "spire",
      "false-dawn",
      "Your lantern answers when the ledger calls your name. Something inside it has been listening since the bridge.",
      "Speak to the lantern's passenger",
      "decision:keeper-secret",
    ),
    "A voice emerges from the flame. It knows the scar under your glove and the words you spoke before you ever reached the town.\n\n“I was your sister,” it says. “Then I was the price you paid.”\n\nYou carried her memory into the Spire thirty years ago to help build the wall. The ritual took your memory of her in return. Maren did not send you to retrieve a light. She sent you to retrieve a witness who could survive beyond the wall.\n\nThe flame bends toward your hand. The voice does not ask to be forgiven. It asks whether you will let it finish speaking.",
    [
      c(
        "Listen, even if it hurts",
        "+2 trust · remember the passenger",
        "Her name is Ilyr. You say it until the lantern stops trembling. The past does not become harmless, but it becomes yours to answer for.",
        { reputation: 2, flag: { key: "ilyr", value: "heard" } },
      ),
      c(
        "Ask what must be done now",
        "+15 energy · keep the memory sealed",
        "Ilyr describes the tide gates beyond the Spire. Her instructions are precise. When you ask nothing about her life, the flame becomes very still.",
        { energy: 15, flag: { key: "ilyr", value: "sealed" } },
      ),
    ],
  ),
  mq(
    "tide-debt",
    "The Ferry with No Shore",
    4,
    "saltreach",
    "keeper-secret",
    "Lysa's ferry can cross the dead tide if someone releases its moorings. The drowned crew has one condition: their last letter must reach the living.",
    "Release the ferry's moorings",
    "event:ferry",
    "salt-compass",
  ),
  mq(
    "admiral",
    "The Admiral's Unpaid Debt",
    4,
    "saltreach",
    "tide-debt",
    "The Admiral claims every passenger owes the sea a life. His helmet contains the contract that made him collector. Break it without losing the ferry's crew.",
    "Defeat the Drowned Admiral",
    "boss:admiral",
    "diver-cuirass",
  ),
  decision(
    mq(
      "dead-letter",
      "A Letter for the Living",
      4,
      "saltreach",
      "admiral",
      "The rescued letter names the people who volunteered to remain beneath the tide. The council's official history calls them traitors.",
      "Deliver the crew's final letter",
      "decision:dead-letter",
    ),
    "Lysa reads the letter by the harbor lamp. Her husband stayed aboard because the ferry carried children whose names the sun had already erased. The crew knew that reaching an ordinary shore would kill them.\n\nMaren called their disappearance a mutiny to keep the last safe harbor from following. Lysa has spent thirty years hating a man who died trying to keep a promise.\n\n“Don't tell me he was a hero,” she says. “Tell me who decided I could not bear the truth.” The letter is hers. The public memorial is still the council's.",
    [
      c(
        "Correct the harbor memorial",
        "+3 trust · the crew's names return",
        "Lysa chisels the first name herself. The memorial becomes crowded with candles, then with stories no council could have written.",
        { reputation: 3, flag: { key: "crew", value: "honored" } },
      ),
      c(
        "Let Lysa decide when to speak",
        "+45 gold · respect her privacy",
        "You give her the original letter and no deadline. A week later, she begins teaching the ferry children to read. The first lesson uses their parents' names.",
        { gold: 45, flag: { key: "crew", value: "private" } },
      ),
    ],
  ),
  mq(
    "ashes-index",
    "The Book That Would Not Burn",
    5,
    "archive",
    "dead-letter",
    "Sella finds an index referring to a third architect of the wall. Its pages rewrite themselves whenever the lantern comes near. Bring back the unburnt folio.",
    "Decode the unburnt folio",
    "event:folio",
    "index-blade",
  ),
  mq(
    "librarian",
    "The Librarian's Final Page",
    5,
    "archive",
    "ashes-index",
    "The Librarian guards the folio's missing page. She believes destroying the witness will spare the town from another dangerous truth.",
    "Defeat the Ash Librarian",
    "boss:librarian",
    "archive-robe",
  ),
  decision(
    mq(
      "third-author",
      "The Third Signature",
      5,
      "archive",
      "librarian",
      "The missing signature is not Maren's, or Ilyr's. It is yours. The surviving page explains what you agreed to forget.",
      "Read your own decree",
      "decision:third-author",
    ),
    "Your signature closes the decree. You designed the wall to preserve people who had already been erased outside it. Every repaired tear consumed one of their memories.\n\nMaren kept it working. Ilyr agreed to become its first witness. You ordered the last safeguard: the architect must forget how the machine was made, so no frightened ruler could turn it into a prison.\n\nThe safeguard worked too well. The darkness became a prison anyway. Sella waits with a blank page. She can publish the design so others can challenge you, or keep the knowledge from anyone who might rebuild it.",
    [
      c(
        "Publish the design and your part in it",
        "+3 trust · weaken the Regent's deception",
        "Sella adds your name without an honorific. For the first time, the town can argue with its own history. The mirrors ahead will have fewer lies to borrow.",
        { reputation: 3, flag: { key: "design", value: "public" } },
      ),
      c(
        "Keep the dangerous instructions sealed",
        "+35 resolve · guard the machine's secret",
        "The folio is sealed with your new oath beside the old signature. You keep the only copy. That choice is protection, and power, at the same time.",
        { resolve: 35, flag: { key: "design", value: "sealed" } },
      ),
    ],
  ),
  mq(
    "star-theft",
    "A Sky Without Witnesses",
    6,
    "observatory",
    "third-author",
    "The observatory's stars are stolen memories. Align the black orrery and find the one reflection that refuses to imitate you.",
    "Solve the black orrery",
    "event:orrery",
    "brass-orrery",
  ),
  mq(
    "regent",
    "The Perfect Kingdom",
    6,
    "observatory",
    "star-theft",
    "The Regent offers a dawn with no grief and no disagreement. The offer requires erasing every person who remembers a different world.",
    "Break the Mirror Regent's rule",
    "boss:regent",
    "mirror-plate",
  ),
  decision(
    mq(
      "reflection",
      "The Other Keeper",
      6,
      "observatory",
      "regent",
      "Behind the Regent's throne waits the reflection you would have become if you had never forgotten. It wants your lantern.",
      "Answer the other keeper",
      "decision:reflection",
    ),
    "The other keeper wears your armor without its dents. Their lantern burns clean and cold. They have repaired the wall a thousand times, and every repair has made its people easier to govern.\n\n“I did not lose anyone,” they say. “I removed the part of them that could leave.”\n\nIlyr recoils inside your lantern. The keeper offers to carry the burden for you. Their world is safe, complete, and silent. Behind them, the mirror children do not blink until permission is given.",
    [
      c(
        "Break the mirror and free its memories",
        "+3 trust · memory pearls enter the Rootsea",
        "The glass falls like rain. Thousands of imperfect voices return at once. Your reflection reaches for the lantern, then dissolves with an expression its sealed mask cannot show.",
        { reputation: 3, flag: { key: "mirror", value: "freed" } },
      ),
      c(
        "Take its knowledge, then close the gate",
        "+25 energy · learn a safer route",
        "You memorize the machine's hidden passages. The gate closes on the silent kingdom. You promise yourself that knowing how to build a cage is not the same as choosing to build one.",
        { energy: 25, flag: { key: "mirror", value: "closed" } },
      ),
    ],
  ),
  mq(
    "memories-wake",
    "The Shore Inside the Sea",
    7,
    "rootsea",
    "reflection",
    "The lost memories gather around a pearl island. Ilyr recognizes the house in its center. Reach it before the tide makes her part of the ocean.",
    "Find Ilyr's remembered home",
    "event:pearl-home",
    "memory-pearl",
  ),
  mq(
    "leviathan",
    "The Sea That Will Not Forget",
    7,
    "rootsea",
    "memories-wake",
    "The Leviathan protects the memories that daylight would erase. It will not let the lantern pass unless you show that an ending can leave someone alive.",
    "Face the Rootsea Leviathan",
    "boss:leviathan",
    "abyss-shell",
  ),
  decision(
    mq(
      "borrowed-heart",
      "A Heart with Room for Two",
      7,
      "rootsea",
      "leviathan",
      "Ilyr can become the Dawn Engine's fuel, return to the Rootsea, or share the burden with you. Only one choice leaves the engine an answer it was not built to accept.",
      "Choose how to carry Ilyr onward",
      "decision:borrowed-heart",
    ),
    "The remembered house contains no battle, no prophecy. Two cups stand beside a cooling loaf. You know which chair was yours.\n\nIlyr is no longer a voice in a flame. She is the warmth that lets you recognize the room. If she powers the engine, the sun returns and her last memory disappears. If she stays in the sea, the wall will continue failing.\n\n“There may be another way,” she says. “But you would have to carry some of the darkness yourself.” The lantern has room for two flames. You have never tried leaving both alight.",
    [
      c(
        "Share the burden with Ilyr",
        "+2 trust · unlock a third ending",
        "You remember the kitchen together. Neither flame consumes the other. The lantern becomes heavier, and the path ahead becomes something neither of you has walked alone.",
        { reputation: 2, flag: { key: "heart", value: "shared" } },
      ),
      c(
        "Accept Ilyr's sacrifice",
        "+45 resolve · restore the old design",
        "She asks you to remember a small ordinary thing when it is over: the smell of bread, not the sound of the bells. You promise, knowing memory is what the machine will take.",
        { resolve: 45, flag: { key: "heart", value: "sacrifice" } },
      ),
      c(
        "Leave her with the remembered shore",
        "+80 gold · refuse the engine's price",
        "Ilyr's warmth settles into the house. Your lantern carries an ember of farewell. You will reach the engine without the fuel it expects, and choose what kind of night remains.",
        { gold: 80, flag: { key: "heart", value: "shore" } },
      ),
    ],
  ),
  {
    ...mq(
      "seven-keys",
      "Three Seals Before Morning",
      8,
      "engine",
      "borrowed-heart",
      "Open the seals of witness, mercy, and change. Each was built to test the architect who would return. Raw strength can break a gate; it cannot answer a question.",
      "Open all three dawn seals",
      "ritual:seals",
      "dawn-key",
    ),
    goal: 3,
  },
  mq(
    "custodian",
    "The Last Custodian",
    8,
    "engine",
    "seven-keys",
    "The Custodian is the safeguard you left behind. It must know whether you have returned to repair your prison, or finally to open it.",
    "Overcome the Dawn Custodian",
    "boss:custodian",
    "dawn-plate",
  ),
  decision(
    mq(
      "new-sun",
      "The Shape of Morning",
      8,
      "engine",
      "custodian",
      "The engine waits for an answer. Vesper's Rest, Ilyr, and the remembered shores will live with the world you choose.",
      "Choose the world's next morning",
      "decision:new-sun",
      "joined-rings",
    ),
    "The great rings stop turning. Through the open gate you see Vesper's Rest: its patched roofs, unfinished memorial, and people who have learned to say the missing names aloud.\n\nThe engine can make the old sun rise. It can also be dismantled, leaving a gentler night that the town must learn to survive. If you brought Ilyr with you, the two flames reveal a third path: a dawn that arrives slowly enough for the remembered to become real.\n\nNo inscription tells you which answer is correct. For the first time, the machine has run out of orders. The morning is yours to begin.",
    [
      c(
        "Restore the old sun",
        "Ending · The Cost of Daylight",
        "The sun rises in one brilliant moment. The wall falls. Ilyr's last warmth leaves the lantern, and the remembered shores become ordinary water. The living plant grain beneath a sky they can finally trust. Every loaf you break afterward carries a memory the engine could not take.",
        { flag: { key: "ending", value: "daylight" } },
      ),
      c(
        "Dismantle the engine",
        "Ending · A Night of Our Own",
        "The great rings are lowered into the sea. Darkness remains, but it no longer feeds on names. Vesper's Rest builds roads between its lanterns. You leave the town with an empty lantern and a map full of places that still deserve to be reached.",
        { flag: { key: "ending", value: "night" } },
      ),
      c(
        "Let the two flames teach a slower dawn",
        "Ending · A Morning Shared · requires shared burden",
        "Dawn returns by degrees: first a pale horizon, then a bird no one remembered, then the warmth of a kitchen window. The Rootsea's people walk ashore with names of their own. Ilyr's flame remains beside yours. The new sun is imperfect, and it leaves everyone room to change.",
        {
          requiresFlag: { key: "heart", value: "shared" },
          flag: { key: "ending", value: "shared" },
        },
      ),
    ],
  ),
];

type SideStory = {
  id: string;
  name: string;
  biome: BiomeId;
  act: number;
  request: string;
  text: string;
  choices: Choice[];
};
export const SIDE_STORIES: SideStory[] = [
  {
    id: "boots",
    name: "The Soldier's Second Pair",
    biome: "catacombs",
    act: 1,
    request:
      "Torren needs the boots his brother left below. The money hidden inside them can pay for a burial, or the new furnace the town needs.",
    text: "Two boots sit beside a flooded cot. One contains a letter; the other, a purse. Torren's brother had been saving to leave Vesper's Rest. The letter asks that he not be buried under the uniform he never wanted.",
    choices: [
      c(
        "Return the boots and the letter",
        "+2 trust",
        "Torren reads the letter twice. His brother is buried in a traveler's coat, and the furnace is repaired by volunteers.",
        { reputation: 2 },
      ),
      c(
        "Use the purse for the furnace",
        "+40 gold · -1 trust",
        "The forge burns brighter. Torren asks once about the letter; you answer without looking at him.",
        { gold: 40, reputation: -1 },
      ),
    ],
  },
  {
    id: "clock",
    name: "The Clock with No Morning",
    biome: "catacombs",
    act: 1,
    request:
      "A watchmaker hears her father's clock ticking beneath the graves. It has kept one hour she cannot account for.",
    text: "The clock's hands move backward whenever you speak. Behind its face, a scrap records the watchmaker's first word. Her father saved the memory instead of the hour the wall demanded.",
    choices: [
      c(
        "Keep the memory inside the clock",
        "+12 resolve",
        "The clock stops counting. At home, the watchmaker hears her father's voice say the word once, and chooses to leave the mechanism still.",
        { resolve: 12 },
      ),
      c(
        "Repair it and return the recorded hour",
        "+20 energy",
        "The hands move forward. The watchmaker winds the clock every evening, even though the hour it gave back belongs to no calendar.",
        { energy: 20 },
      ),
    ],
  },
  {
    id: "bread",
    name: "Bread for the Unburied",
    biome: "catacombs",
    act: 1,
    request:
      "The baker leaves bread on the lower stairs. Someone has begun leaving a coin in return. Find out who is still hungry.",
    text: "A sealed-helmet watchman sits beside the bread basket. He cannot eat, but placing the loaf on his knees keeps him from forgetting the bakery. His coin bears the baker's old wedding date.",
    choices: [
      c(
        "Sit with him until the bell quiets",
        "+2 trust · heal 18 HP",
        "He sets the coin beside you and finally rests. The baker keeps leaving bread, but now she brings a chair.",
        { reputation: 2, hp: 18 },
      ),
      c(
        "Carry his coin to the baker",
        "+25 gold",
        "The baker recognizes it before you finish speaking. She pays for your trouble, then closes the shop early.",
        { gold: 25 },
      ),
    ],
  },
  {
    id: "needle",
    name: "The Seamstress's Missing Thread",
    biome: "thornwild",
    act: 2,
    request:
      "Reth's mourning cloth unravels every night. Find the moth carrying the last memory of the person it was made for.",
    text: "A moth rests on a black needle. Its wing shows a hand threading cloth, then a different hand wearing it. The mourning veil was made for someone who chose to leave, not someone who died.",
    choices: [
      c(
        "Return the needle without the moth",
        "+2 trust",
        "Reth puts away the mourning veil. She begins a bright travel scarf instead. The moth follows the person it remembers.",
        { reputation: 2 },
      ),
      c(
        "Bring both back safely",
        "+15 resolve · gain silk armor",
        "Reth keeps the moth in an open window. Some evenings it leaves, and some evenings she lets it.",
        { resolve: 15, item: "ash-cloak" },
      ),
    ],
  },
  {
    id: "fox",
    name: "The Fox That Knows the Road",
    biome: "thornwild",
    act: 2,
    request:
      "A fox leads travelers in circles. Oren wants it trapped. Nera believes it is keeping people away from something worse.",
    text: "The fox's pawprints stop at a root-filled sinkhole. Beyond it, a human whistle repeats without a body to breathe it. The animal returns and waits for you to understand.",
    choices: [
      c(
        "Mark the safe route it showed you",
        "Open a shortcut · +2 trust",
        "Travelers begin following small white arrows. The fox keeps watch at the old whistle, and stops wasting its warnings on those who listen.",
        { shortcut: true, reputation: 2 },
      ),
      c(
        "Bring proof to Captain Oren",
        "+35 gold",
        "Oren withdraws the traps. He refuses to thank a fox, so the reward goes to you.",
        { gold: 35 },
      ),
    ],
  },
  {
    id: "orchard",
    name: "Fruit from a Borrowed Summer",
    biome: "thornwild",
    act: 2,
    request:
      "The orchard bears fruit in winter. Its keeper asks whether feeding the hungry with another person's memory is theft.",
    text: "Each apple contains a summer someone has forgotten. The oldest tree carries the memory of a farmer who died feeding the town. It continues giving without anyone remembering to ask.",
    choices: [
      c(
        "Plant the seeds beside the shrine",
        "+2 trust · heal 22 HP",
        "The shrine grows a small ordinary orchard. Its first harvest tastes of rain rather than memory.",
        { reputation: 2, hp: 22 },
      ),
      c(
        "Harvest enough for the hungry",
        "+30 resolve",
        "Every bowl is filled. At the meal, you tell the farmer's story so the gift has a name again.",
        { resolve: 30 },
      ),
    ],
  },
  {
    id: "stairs",
    name: "The Stairmaker's Last Step",
    biome: "spire",
    act: 3,
    request:
      "The Spire's builder left one staircase unfinished. His apprentice wants the final step, not a monument.",
    text: "The last stair hangs above an open shaft. A mason's note explains that it was left out to stop the council from carrying prisoners into the engine chamber. The apprentice has been repairing an act of resistance.",
    choices: [
      c(
        "Build a way around the prison door",
        "Open shortcut · +2 trust",
        "The apprentice finishes a route to the public gallery instead. A staircase becomes useful without completing the cruelty it was designed to serve.",
        { shortcut: true, reputation: 2 },
      ),
      c(
        "Preserve the missing step",
        "+20 resolve",
        "A rail and a small plaque keep travelers safe. The gap remains, with its reason written plainly.",
        { resolve: 20 },
      ),
    ],
  },
  {
    id: "gloves",
    name: "Hands That Cannot Touch",
    biome: "spire",
    act: 3,
    request:
      "The shrine keeper needs the gauntlets of a worker whose hands became too hot to hold his child.",
    text: "The gauntlets rest beside a small wooden toy. Their owner fed the engine until the fire stayed in his skin. The toy's handle was padded with the last cloth he could bear to touch.",
    choices: [
      c(
        "Return the toy with the gauntlets",
        "+3 trust",
        "His daughter keeps the toy, then donates the gauntlets to workers who still need them. No one is asked to become a monument.",
        { reputation: 3 },
      ),
      c(
        "Reforge the gauntlets for the town",
        "+45 gold · gain armor",
        "Torren turns them into heat shields. He places the toy on the forge's coldest shelf.",
        { gold: 45, item: "bellplate" },
      ),
    ],
  },
  {
    id: "bird",
    name: "The Bird in the Bell Tower",
    biome: "spire",
    act: 3,
    request:
      "A bird sings a dawn song in the dark. Sella wants a recording; the tower keeper wants one uninterrupted hour of sleep.",
    text: "The bird sings only while the keeper's lamp is lit. It learned the tune from him before he forgot what morning sounded like. Neither remembers teaching the other.",
    choices: [
      c(
        "Move the lamp to an open window",
        "+2 trust",
        "The song reaches the sleeping streets at a gentler distance. The keeper sleeps, and the bird finally leaves its cage.",
        { reputation: 2 },
      ),
      c(
        "Write down the song's rhythm",
        "+20 energy",
        "Sella records the pattern rather than trapping the singer. The archive gains a page that does not need a cage.",
        { energy: 20 },
      ),
    ],
  },
  {
    id: "anchor",
    name: "An Anchor for an Empty Boat",
    biome: "saltreach",
    act: 4,
    request:
      "Lysa needs an anchor to stop a boat returning without its crew every night.",
    text: "The empty boat carries bowls set for supper. Its anchor is caught around a pearl that keeps repeating the moment before the storm. Freeing the anchor will end the supper the crew never finished.",
    choices: [
      c(
        "Set the table, then release the pearl",
        "+3 trust · heal 35 HP",
        "You leave a place for every sailor. When the anchor rises, the boat drifts home once and stays.",
        { reputation: 3, hp: 35 },
      ),
      c(
        "Keep the pearl for the families",
        "+45 gold · gain tide bell",
        "The families pass the pearl from hand to hand. It shows a meal rather than a death, which is enough for now.",
        { gold: 45, item: "tide-bell" },
      ),
    ],
  },
  {
    id: "net",
    name: "The Netmaker's Open Knot",
    biome: "saltreach",
    act: 4,
    request:
      "A net catches memories instead of fish. The netmaker asks you to recover it before someone sells what should belong to the sea.",
    text: "The net holds a baby's first laugh, a failed apology, and the smell of a summer storm. One knot has been tied so anything frightened can escape.",
    choices: [
      c(
        "Untie the remaining knots",
        "+2 trust · open shortcut",
        "The memories return to their currents. The loose net becomes a bridge across the harbor's broken stairs.",
        { reputation: 2, shortcut: true },
      ),
      c(
        "Return it with its open knot intact",
        "+35 resolve",
        "The netmaker keeps the empty places in his design. Catching enough, he says, does not mean catching everything.",
        { resolve: 35 },
      ),
    ],
  },
  {
    id: "toll",
    name: "The Ferryman's Last Coin",
    biome: "saltreach",
    act: 4,
    request:
      "A ferryman charges one coin to return a lost name. His daughter needs him to stop buying passengers with his own memory.",
    text: "The ferryman has forgotten his daughter's age, then her birthday, then why she waits on the shore. His toll box is empty because he pays for those who cannot.",
    choices: [
      c(
        "Pay the toll for his waiting passengers",
        "25 gold · +4 trust",
        "His daughter takes his hand before another crossing. The boat continues under a different ferryman, paid by a town that finally knows what the fare costs.",
        { gold: -25, requiresGold: 25, reputation: 4 },
      ),
      c(
        "Help his daughter bring him home",
        "+25 resolve",
        "She tells him ordinary stories all the way back. By the third, he remembers that he likes being told them.",
        { resolve: 25 },
      ),
    ],
  },
  {
    id: "ink",
    name: "The Ink That Refuses a Lie",
    biome: "archive",
    act: 5,
    request:
      "Sella's new ink erases every false sentence. A council clerk has hidden the bottle beneath the archive.",
    text: "The bottle stands beside a confession whose last line remains blank. The clerk stole food, then spent years recording every debt as though hunger were a crime.",
    choices: [
      c(
        "Bring the ink and the unfinished confession",
        "+3 trust",
        "The confession names the hungry before it names the thief. The council's records begin leaving room for reasons.",
        { reputation: 3 },
      ),
      c(
        "Give the clerk a chance to finish it",
        "+55 gold",
        "He writes through the night. His final sentence survives the ink: he should have asked for help.",
        { gold: 55 },
      ),
    ],
  },
  {
    id: "margin",
    name: "The Person in the Margin",
    biome: "archive",
    act: 5,
    request:
      "A reader has become trapped between two pages. The Librarian calls him a damaged annotation.",
    text: "The reader speaks through a penciled door. Every correction erases a little of his room. He asks you to leave one mistake in the book so he can keep a place to live.",
    choices: [
      c(
        "Leave the mistake and open the door",
        "+3 trust · heal 40 HP",
        "The reader steps out with an ink-stained coat. The book is less perfect, and one more person gets to read it.",
        { reputation: 3, hp: 40 },
      ),
      c(
        "Copy his room into a new notebook",
        "+30 energy",
        "He keeps his penciled window. You leave the new book open beside the old one so moving will remain his choice.",
        { energy: 30 },
      ),
    ],
  },
  {
    id: "recipe",
    name: "A Recipe for a Lost Winter",
    biome: "archive",
    act: 5,
    request:
      "The baker's recipe book lists a dish no one can remember. Its missing page may feed more than hunger.",
    text: "The recipe is written for thirty children who never reached the harbor. It measures enough flour for an absence. A note says to keep making it until the table is full again.",
    choices: [
      c(
        "Bring the page to the harbor kitchens",
        "+4 trust",
        "The ferry children help knead the dough. The old measurements finally feed living hands.",
        { reputation: 4 },
      ),
      c(
        "Preserve the original in the archive",
        "+45 resolve",
        "Sella makes copies for every kitchen. The original is kept for its handwriting, rather than its grief.",
        { resolve: 45 },
      ),
    ],
  },
  {
    id: "double",
    name: "The Tailor's Other Customer",
    biome: "observatory",
    act: 6,
    request:
      "A reflected customer keeps returning clothes that fit perfectly. The tailor needs to know what remains wrong.",
    text: "The customer wants a coat with a loose seam, a crooked button, a repair. In the mirror kingdom, nothing fits badly enough to prove anyone has lived in it.",
    choices: [
      c(
        "Give the coat one honest repair",
        "+3 trust",
        "The customer touches the seam as though it were a letter from home. When they leave the mirror, the coat comes with them.",
        { reputation: 3 },
      ),
      c(
        "Teach the tailor to leave room for change",
        "+60 gold",
        "The new patterns contain extra cloth and removable hems. The mirror customers stop asking to be made perfect.",
        { gold: 60 },
      ),
    ],
  },
  {
    id: "stars",
    name: "Stars for the Missing Sailor",
    biome: "observatory",
    act: 6,
    request:
      "A navigator remembers a constellation that no longer exists. Recover its brass chart before the Regent makes another sky official.",
    text: "The missing constellation is shaped like the navigator's mother's hands. She invented it to guide him home before he learned the real stars. The Regent erased it because it was not accurate.",
    choices: [
      c(
        "Restore the private constellation",
        "+3 trust · open shortcut",
        "A small brass chart becomes a key through the observatory. The stars need not be true to have guided someone honestly.",
        { reputation: 3, shortcut: true },
      ),
      c(
        "Map it alongside the official stars",
        "+35 energy",
        "Sella marks the chart as a story, not an error. Sailors begin adding constellations of their own.",
        { energy: 35 },
      ),
    ],
  },
  {
    id: "window",
    name: "The Window That Remembers Rain",
    biome: "observatory",
    act: 6,
    request:
      "A widow's mirror shows rain falling on an empty chair. She asks for a way to see something else without losing the chair.",
    text: "The reflection is not a prison. It is a room someone kept visiting because no one offered another place to sit. You can open its window without taking the chair away.",
    choices: [
      c(
        "Open the reflected window",
        "+3 trust · heal 45 HP",
        "Real rain reaches the glass. The widow moves the chair to her kitchen, where visitors can use it.",
        { reputation: 3, hp: 45 },
      ),
      c(
        "Carry the chair into the living room",
        "+30 resolve",
        "The mirror grows quiet. The chair remains a memory, and becomes furniture again.",
        { resolve: 30 },
      ),
    ],
  },
  {
    id: "shell",
    name: "A Shell for a Quiet Voice",
    biome: "rootsea",
    act: 7,
    request:
      "A child hears arguments inside a shell. Find the memory that needs to finish speaking before it can be silent.",
    text: "Two voices repeat their final disagreement. Neither remembers what it concerned. Beneath them, a third voice asks whether supper will be late.",
    choices: [
      c(
        "Let the child's question be heard",
        "+4 trust",
        "The argument ends with an ordinary apology. The shell carries only the sea when you return it.",
        { reputation: 4 },
      ),
      c(
        "Set the shell beside a remembered home",
        "+40 resolve",
        "The voices follow the smell of cooking. Some endings need a room, not a verdict.",
        { resolve: 40 },
      ),
    ],
  },
  {
    id: "garden",
    name: "The Garden Under the Ocean",
    biome: "rootsea",
    act: 7,
    request:
      "A gardener grows flowers where no living hand can reach. His granddaughter wants to bring one ashore.",
    text: "The flowers are memories of days he spent with her. Picking one will not destroy the garden. It will let a day belong to someone who is still growing.",
    choices: [
      c(
        "Choose the day she remembers too",
        "+4 trust · heal 55 HP",
        "The flower survives the surface. She plants it in a pot large enough for next year.",
        { reputation: 4, hp: 55 },
      ),
      c(
        "Bring a seed rather than a flower",
        "+45 energy",
        "The seed grows a color neither of them remembers. The garden finally makes something new.",
        { energy: 45 },
      ),
    ],
  },
  {
    id: "bottle",
    name: "The Message That Arrived First",
    biome: "rootsea",
    act: 7,
    request:
      "A bottle contains a letter from tomorrow. It asks a living sailor to forgive a betrayal that has not happened.",
    text: "The future letter describes a panic, a cut rope, and a friend abandoned. The sea has sent the apology early enough for the rope to remain uncut.",
    choices: [
      c(
        "Warn both sailors together",
        "+4 trust · open shortcut",
        "They agree on a signal before setting sail. The letter fades, leaving a bottle useful for clean water.",
        { reputation: 4, shortcut: true },
      ),
      c(
        "Return the letter unopened to its author",
        "+80 gold",
        "The sailor reads it alone, then asks his friend to share command of the boat. You accept payment for delivering a future that no longer needs to happen.",
        { gold: 80 },
      ),
    ],
  },
  {
    id: "candle",
    name: "One Candle After Dawn",
    biome: "engine",
    act: 8,
    request:
      "The shrine keeper wants a candle that will survive sunrise, for the people daylight might otherwise erase.",
    text: "The candle burns without consuming its wick. Its wax is made from promises kept by ordinary hands. The engine cannot measure such a fuel.",
    choices: [
      c(
        "Share its flame with the waiting town",
        "+5 trust",
        "Every window keeps one candle. The town is prepared to remember even when it no longer needs the light.",
        { reputation: 5 },
      ),
      c(
        "Place it before the engine's gate",
        "+50 resolve",
        "The flame shows a path through the machinery that the old plans did not include.",
        { resolve: 50 },
      ),
    ],
  },
  {
    id: "wheel",
    name: "The Engineer's Unfinished Wheel",
    biome: "engine",
    act: 8,
    request:
      "Torren's apprentice designed a wheel that turns in both directions. The old engine rejects it as a defect.",
    text: "The wheel can undo one movement without destroying the next. The apprentice calls this repair. The Custodian calls it disobedience.",
    choices: [
      c(
        "Install the reversible wheel",
        "+4 trust · open shortcut",
        "For the first time, the machine can admit a mistake without making it permanent. The apprentice signs her work.",
        { reputation: 4, shortcut: true },
      ),
      c(
        "Take the design back to the forge",
        "+100 gold",
        "Torren builds smaller wheels for the town's lifts. A safer way home matters before the great machine ever turns.",
        { gold: 100 },
      ),
    ],
  },
  {
    id: "table",
    name: "A Place at the Morning Table",
    biome: "engine",
    act: 8,
    request:
      "Nera asks you to leave room in the new world for those who were born from borrowed memories.",
    text: "A stone table stands before the dawn gate. Its seats are labeled for the living and the dead. Nera lays an unnamed wooden stool between them.",
    choices: [
      c(
        "Keep the stool where she placed it",
        "+5 trust",
        "The dawn gate accepts a seat it has no category for. You remember that a person does not become less real because a machine lacks the right word.",
        { reputation: 5 },
      ),
      c(
        "Erase every label from the table",
        "+50 energy",
        "The table becomes a place to sit. Nothing else is required.",
        { energy: 50 },
      ),
    ],
  },
];

const event = (
  id: string,
  name: string,
  biome: BiomeId,
  text: string,
  choices: Choice[],
  marker = id,
): StoryEvent => ({
  id,
  name,
  biome,
  text,
  choices,
  marker,
  eyebrow: "A STORY IN THE HOLLOW",
  art:
    Math.max(
      0,
      [
        "catacombs",
        "thornwild",
        "spire",
        "saltreach",
        "archive",
        "observatory",
        "rootsea",
        "engine",
      ].indexOf(biome),
    ) <= 2
      ? ["catacombs", "thornwild", "spire"].indexOf(biome)
      : 4 +
        ["saltreach", "archive", "observatory", "rootsea", "engine"].indexOf(
          biome,
        ),
});
export const EXTRA_EVENTS: StoryEvent[] = [
  event(
    "ledger",
    "The Warden's Ledger",
    "catacombs",
    "Names fill the copper-bound ledger. Some have been crossed out; others have been written back in a different hand. The final entry is yours, dated tomorrow. A second column reads: witness recovered. The Warden was guarding the ledger from the council, not guarding the dead from you.",
    [
      c(
        "Carry it intact to Maren",
        "+10 resolve · recover evidence",
        "You wrap the ledger in dry cloth. The bell's final vibration fades from its copper spine.",
        { resolve: 10 },
      ),
      c(
        "Make a copy for Sella first",
        "Will 4 · +2 trust",
        "Sella will receive every page, including the margins. No single locked drawer can hold the whole story now.",
        { requiresAttribute: { id: "will", value: 4 }, reputation: 2 },
      ),
    ],
  ),
  event(
    "cocoon",
    "The Unopened Cocoon",
    "thornwild",
    "A child wakes inside a cocoon the Sovereign refused to cut open. The two names on its silk belong to a drowned woman and a girl who was never born. The child asks for water before she asks who she is. That ordinary request is the first thing here that has not been borrowed.",
    [
      c(
        "Help her reach the town",
        "+3 trust · rescue the child",
        "She walks beside your lantern and chooses not to follow the moths. At the gate, she says she will decide what to be called tomorrow.",
        { reputation: 3 },
      ),
      c(
        "Let her gather her memories first",
        "+20 resolve · protect her choice",
        "You wait while she folds the empty cocoon. She brings it as a blanket, not as proof of who she must become.",
        { resolve: 20 },
      ),
    ],
  ),
  event(
    "dawn-lens",
    "The Fuel Ledger",
    "spire",
    "Three lenses point toward a cold flame. The marks beneath them name sun, shelter, and witness. A fourth mark has been scraped away. Your lantern casts its shadow into that empty space, and the engine begins showing the memories it consumed.",
    [
      c(
        "Align witness before shelter",
        "+20 energy · reveal the missing record",
        "The ledger resolves into ordinary rooms and interrupted meals. The missing column is not fuel. It is consent.",
        { energy: 20 },
      ),
      c(
        "Use your own lantern as the fourth lens",
        "Will 6 · +2 trust",
        "The engine speaks a name you cannot remember. Your flame answers with a voice that is not yours.",
        { requiresAttribute: { id: "will", value: 6 }, reputation: 2 },
      ),
    ],
  ),
  event(
    "ferry",
    "The Ferry's Moorings",
    "saltreach",
    "Four ropes hold Lysa's ferry to a shore that no longer exists. The crew's sealed masks turn toward the letter in your hand. They do not want another life as payment. They want someone to know why they stayed.",
    [
      c(
        "Promise to deliver their letter",
        "+3 trust · release the ferry",
        "The ropes loosen without a knife. The ferry moves when its crew finally believes the living will listen.",
        { reputation: 3 },
      ),
      c(
        "Pay for every unfinished crossing",
        "30 gold · gain a tide bell",
        "The coins sink. The crew gives them back as a small silent bell, and casts off.",
        { requiresGold: 30, gold: -30, item: "tide-bell" },
      ),
    ],
  ),
  event(
    "folio",
    "The Unburnt Folio",
    "archive",
    "Ash drifts upward from an open book. Its index contains your name under architect, witness, and condemned. The last category has been corrected three times. The corrections belong to Maren, Ilyr, and a hand you recognize as your own.",
    [
      c(
        "Read all three corrections",
        "+25 resolve · recover the folio",
        "Each correction is an attempt to leave you a way back. The final page has been taken to the Librarian's veil.",
        { resolve: 25 },
      ),
      c(
        "Copy the index into your journal",
        "Will 8 · +3 trust",
        "The ash stops climbing when the words exist somewhere the fire does not control.",
        { requiresAttribute: { id: "will", value: 8 }, reputation: 3 },
      ),
    ],
  ),
  event(
    "orrery",
    "The Black Orrery",
    "observatory",
    "The machine offers three skies: one without loss, one without disagreement, and one without a sun. Only the third contains stars that move when nobody orders them to. A small empty socket waits for your lantern.",
    [
      c(
        "Choose the sky that can still change",
        "+25 energy · align the orrery",
        "The false stars dim. Behind them, the Regent's throne appears as an empty chair held up by reflections.",
        { energy: 25 },
      ),
      c(
        "Remove the mirror at the center",
        "Agility 9 · open shortcut",
        "The mechanism keeps turning around an honest absence. A passage opens beneath the observation ring.",
        { requiresAttribute: { id: "agility", value: 9 }, shortcut: true },
      ),
    ],
  ),
  event(
    "pearl-home",
    "Two Cups Beside the Window",
    "rootsea",
    "The pearl island holds a kitchen you recognize before memory gives you permission. Two cups stand by the window. One has a chipped handle you once promised to repair. Ilyr's flame moves toward it as though the cup were a shore.",
    [
      c(
        "Remember the unfinished repair",
        "+30 resolve · reach the remembered home",
        "You hold the chipped cup. Ilyr tells you that she kept using it. The small fact hurts more gently than the great truth did.",
        { resolve: 30 },
      ),
      c(
        "Light the window for anyone still lost",
        "+3 trust",
        "Other pearl islands answer with their own windows. The Rootsea becomes a neighborhood, one light at a time.",
        { reputation: 3 },
      ),
    ],
  ),
  ...["witness", "mercy", "change"].map((seal, index) =>
    event(
      `seal-${seal}`,
      `The Seal of ${seal[0].toUpperCase() + seal.slice(1)}`,
      "engine",
      [
        "A sealed helm faces a blank ledger. The gate asks whether a truth remains yours when it makes you ashamed. It will accept an answer spoken without a title.",
        "Three candles stand before an empty chair. The gate asks whether a person must be useful to deserve a morning. Your lantern is the only measure it can see.",
        "A wheel turns in a perfect circle. The gate asks whether a promise may change when keeping it would become cruel. One spoke has been left unfinished.",
      ][index],
      [
        c(
          [
            "Name your part in the Dimming",
            "Light the empty chair",
            "Leave the unfinished spoke free",
          ][index],
          "+15 resolve · open a dawn seal",
          [
            "The ledger writes your name without erasing anyone else's.",
            "The third candle catches. The chair remains empty, and remains welcome.",
            "The wheel takes one imperfect turn. The gate opens on a path nobody has measured.",
          ][index],
          { resolve: 15, marker: `seal:${seal}` },
        ),
        c(
          "Answer with the townspeople's stories",
          "+2 trust · open a dawn seal",
          [
            "The ledger writes the baker's account beside the architect's. Both remain legible when the first gate opens.",
            "The empty chair fills with the ferryman's ordinary promises. The second gate opens for someone who never built a machine.",
            "The child describes a tomorrow nobody planned. The last gate opens toward a morning the engine cannot predict.",
          ][index],
          { reputation: 2, marker: `seal:${seal}` },
        ),
      ],
      `seal:${seal}`,
    ),
  ),
  ...SIDE_STORIES.map((s) => event(s.id, s.name, s.biome, s.text, s.choices)),
  event(
    "flood-gate",
    "A Tide Between the Stones",
    "saltreach",
    "Black water is climbing the narrow passage. A loose chain can close the gate, but it will also trap a distant lantern on the other side.",
    [
      c(
        "Hold the gate until the lantern passes",
        "Might 7 · -12 HP · +3 trust",
        "A masked porter crawls through before you release the chain. They leave a small medicine tin beside your boots.",
        {
          requiresAttribute: { id: "might", value: 7 },
          hp: -12,
          reputation: 3,
        },
      ),
      c(
        "Find the maintenance stair",
        "Open shortcut · -8 resolve",
        "The stair reaches both sides of the gate. You return for the porter before the water hides the path.",
        { shortcut: true, resolve: -8 },
      ),
    ],
  ),
  event(
    "cipher-lock",
    "The Lock Made of Corrections",
    "archive",
    "Four brass words can be arranged on the door: I, WAS, WRONG, and ONCE. The lock closes whenever ONCE is used to excuse the rest.",
    [
      c(
        "Leave ONCE outside the sentence",
        "+20 energy · open shortcut",
        "I WAS WRONG. The door opens without asking for the mistake to become permanent.",
        { energy: 20, shortcut: true },
      ),
      c(
        "Break the frame and keep the words",
        "Might 10 · gain a relic",
        "The words survive the broken frame. Torren can use them on a door that does not need shame as a key.",
        { requiresAttribute: { id: "might", value: 10 }, item: "oath-scroll" },
      ),
    ],
  ),
  event(
    "mirror-path",
    "The Path That Looks Back",
    "observatory",
    "Three passages reflect your lantern. In two, the flame moves before your hand. The third reflection is late by one honest heartbeat.",
    [
      c(
        "Follow the reflection that is late",
        "Open shortcut · +10 resolve",
        "The false passages fold into the glass. Your shadow follows rather than leads.",
        { shortcut: true, resolve: 10 },
      ),
      c(
        "Cover the mirrors and feel the floor",
        "Agility 8 · heal 25 HP",
        "Without a borrowed sky, the floor's old markings guide your feet.",
        { requiresAttribute: { id: "agility", value: 8 }, hp: 25 },
      ),
    ],
  ),
  event(
    "root-surge",
    "The Roots Hold Their Breath",
    "rootsea",
    "The ocean withdraws from the passage. Roots tighten around glass bottles that will shatter when the tide returns. One bottle contains a lullaby; another, a route home.",
    [
      c(
        "Brace the bottles with your cloak",
        "-18 HP · +4 trust",
        "The tide bruises your arms, but the lullaby returns to a child on the shore.",
        { hp: -18, reputation: 4 },
      ),
      c(
        "Guide the roots around the current",
        "Will 9 · open shortcut",
        "The roots learn the tide's rhythm. A dry arch remains after the water passes.",
        { requiresAttribute: { id: "will", value: 9 }, shortcut: true },
      ),
    ],
  ),
];

export const SIDE_QUESTS: Quest[] = [
  ...SIDE_STORIES.map((s) => ({
    id: `side-${s.id}`,
    name: s.name,
    type: "Side quest" as const,
    chapter: `People of ${ROMANS[s.act - 1]} · A life beyond the main story`,
    description: s.request,
    objective: `Resolve ${s.name}`,
    objectiveKey: `event:${s.id}`,
    goal: 1,
    gold: 25 + s.act * 22,
    xp: 25 + s.act * 18,
    biome: s.biome,
    requires:
      s.act === 1
        ? undefined
        : [
            "",
            "",
            "testimony",
            "changeling",
            "keeper-secret",
            "dead-letter",
            "third-author",
            "reflection",
            "borrowed-heart",
          ][s.act],
  })),
  ...(
    [
      "catacombs",
      "thornwild",
      "spire",
      "saltreach",
      "archive",
      "observatory",
      "rootsea",
      "engine",
    ] as BiomeId[]
  ).map((biome, i) => ({
    id: `survey-${biome}`,
    name: [
      "The Lower Stairs",
      "Paths Between the Roots",
      "A Map Above the Bells",
      "The Harbor's Safe Crossings",
      "Rooms the Fire Missed",
      "An Honest Star Chart",
      "The Remembered Shores",
      "A Road Through the Morning",
    ][i],
    type: "Side quest" as const,
    chapter: "The Surveyors' Guild",
    description: [
      "Oren needs a route that an injured porter can follow. Mark eight rooms beneath the sanctuary.",
      "Nera wants a path through the wood that does not ask travelers to surrender a name.",
      "The stairmakers need a record of the upper landings before repairs can begin.",
      "Lysa can bring supplies home if the lower harbor crossings are mapped.",
      "Sella wants to rescue books from rooms the official index says never existed.",
      "The navigators need a chart that records what the mirrors conceal, rather than what they show.",
      "Families wait to discover which remembered shores can still be reached.",
      "Torren's apprentices will follow your map to dismantle or repair the machine safely.",
    ][i],
    objective: `Explore ${8 + i * 2} distinct rooms in this region`,
    objectiveKey: `rooms:${biome}`,
    goal: 8 + i * 2,
    gold: 50 + i * 35,
    xp: 45 + i * 25,
    biome,
    requires:
      i === 0
        ? undefined
        : [
            "testimony",
            "changeling",
            "keeper-secret",
            "dead-letter",
            "third-author",
            "reflection",
            "borrowed-heart",
          ][i - 1],
  })),
];

export const INTRO_PAGES = [
  {
    eyebrow: "THE LAST ORDINARY MORNING",
    title: "The sun did not go out all at once.",
    text: "At first, people blamed the weather. Then the harbor lost a street, though its stones were still there. A mother forgot the child standing beside her. By winter, daylight had begun taking more than warmth.",
    art: 0,
  },
  {
    eyebrow: "THIRTY YEARS OF CANDLELIGHT",
    title: "One town learned to live without it.",
    text: "Vesper's Rest raised a wall of darkness around the people the sun could no longer recognize. Bread was baked by lantern light. Children learned the stars from old books. No one agreed on what had been lost outside.",
    art: 1,
  },
  {
    eyebrow: "THE FIRST THING TO DISAPPEAR",
    title: "Then the names began to leave.",
    text: "White moths settled on pillows. By morning, a familiar face had become a stranger behind a cloth mask. The council called it a sickness. The children called it the forest asking them to come home.",
    art: 2,
  },
  {
    eyebrow: "BENEATH THE SANCTUARY",
    title: "Tonight, the drowned bell rings.",
    text: "It has been silent since the lower stairs were sealed. Now it tolls once for every name in the Warden's ledger. The last name has been written in your hand. Its date is tomorrow.",
    art: 3,
  },
  {
    eyebrow: "A PROMISE YOU CANNOT REMEMBER",
    title: "Maren gives you a lantern.",
    text: "The elder's gloves hide hands too young for her voice. She asks you to descend before the council hears the bell. When you touch the lantern, the flame leans toward you as though it has been waiting to be recognized.",
    art: 4,
  },
  {
    eyebrow: "THE ROAD YOU HAVE WALKED BEFORE",
    title: "Your shadow knows the bridge.",
    text: "You remember arriving at the town. You do not remember choosing the road. In a broken window, your reflection holds a lantern brighter than yours. It turns away before you do.",
    art: 5,
  },
  {
    eyebrow: "SOMETHING TRAVELS WITH YOU",
    title: "A voice beneath the flame.",
    text: "At the sanctuary door, you hear a woman say your name. The street behind you is empty. The voice comes from the lantern, quiet enough to mistake for memory: this time, let me finish speaking.",
    art: 6,
  },
  {
    eyebrow: "THE LANTERN OATH",
    title: "Carry a light. Leave room for a dawn.",
    text: "You fasten your mask and step below. The town needs an answer. The bell needs a witness. Whatever waits in the darkness, you will decide what deserves to be brought back into the morning.",
    art: 7,
  },
];
