import type { StoryEvent, BiomeId, Choice } from "./data";
const crossing = (
  id: string,
  name: string,
  biome: BiomeId,
  art: number,
  kind: "puzzle" | "hazard",
  text: string,
  choices: Choice[],
): StoryEvent => ({
  id,
  name,
  biome,
  art,
  kind,
  text,
  eyebrow: kind === "puzzle" ? "A QUESTION IN STONE" : "THE LAND HAS A SAY",
  choices,
});
const answer = (
  label: string,
  hint: string,
  outcome: string,
  more: Partial<Choice> = {},
): Choice => ({ label, hint, outcome, ...more });
export const CROSSINGS: StoryEvent[] = [
  crossing(
    "weight-of-bells",
    "The Bell Counterweights",
    "catacombs",
    0,
    "puzzle",
    "Three bell ropes hang over a flooded stair. One pulls upward, one pulls down, and one has been cut. A scratched note reads: the quiet rope holds what the others have forgotten.",
    [
      answer(
        "Pull the cut rope's hidden end",
        "Open a shortcut · +8 energy",
        "The broken end runs behind the wall. A dry service stair opens, skipping the flooded galleries.",
        { shortcut: true, energy: 8 },
      ),
      answer(
        "Climb the maintenance ladder",
        "Lose 4 health · safer footing",
        "You leave the mechanism alone. The ladder shivers under your boots, but its upper landing is sound.",
        { hp: -4 },
      ),
    ],
  ),
  crossing(
    "rising-tomb",
    "A Tomb at High Water",
    "catacombs",
    0,
    "hazard",
    "Water rises through the lid of a tomb instead of around it. A porter’s pack floats against a iron grille. Reaching it means trusting stone that is already moving.",
    [
      answer(
        "Brace the lid and retrieve the pack",
        "Might 5 · gain 28 gold",
        "You set your shoulder beneath the slab. The pack holds the porter's wages, wrapped twice against the water.",
        { requiresAttribute: { id: "might", value: 5 }, gold: 28 },
      ),
      answer(
        "Mark the current and cross the upper ledge",
        "Gain 6 resolve",
        "You scratch a warning into the ledge. The next traveler will know where the water lies.",
        { resolve: 6 },
      ),
    ],
  ),
  crossing(
    "root-knot",
    "The Root That Lies",
    "thornwild",
    1,
    "puzzle",
    "A root bridge repeats every word you speak, except your name. The carvings below it show people crossing backward, looking at the shore they have chosen to leave.",
    [
      answer(
        "Walk backward without offering a name",
        "Open a shortcut · +8 resolve",
        "The roots loosen beneath your heels. You reach a clearing that the ordinary path circles for miles.",
        { shortcut: true, resolve: 8 },
      ),
      answer(
        "Follow the old deer trail",
        "Gain 10 energy",
        "The deer has made no promises to the wood. Its trail carries you around the knot without a bargain.",
        { energy: 10 },
      ),
    ],
  ),
  crossing(
    "moth-storm",
    "A Storm of Borrowed Voices",
    "thornwild",
    1,
    "hazard",
    "Moths gather so thickly that the path loses its edges. Each calls in a voice you almost know. Your mask catches the first cold touch of their wings.",
    [
      answer(
        "Shield the lantern and wait",
        "Spend 5 energy · gain 10 resolve",
        "The voices exhaust themselves against your covered flame. When they depart, you can still remember why you came.",
        { energy: -5, resolve: 10 },
      ),
      answer(
        "Take shelter beneath a hollow trunk",
        "Lose 5 health · gain 8 energy",
        "Thorns scratch your armor at the entrance. Inside, a dry nest gives you a place to breathe.",
        { hp: -5, energy: 8 },
      ),
    ],
  ),
  crossing(
    "unrung-stair",
    "The Unrung Stair",
    "spire",
    2,
    "puzzle",
    "Every third step rings a bell. A plaque says the architects measured silence, not height. Above you, a soot-covered landing hangs where no stair seems to reach.",
    [
      answer(
        "Step between the ringing stones",
        "Agility 5 · open a shortcut",
        "You find the empty beats in the stair's rhythm. A suspended walkway carries you across two ruined landings.",
        { requiresAttribute: { id: "agility", value: 5 }, shortcut: true },
      ),
      answer(
        "Turn the plaque toward the wall",
        "Gain 12 energy",
        "Behind the plaque, you find a maintenance lever. The nearest flight settles gently into place.",
        { energy: 12 },
      ),
    ],
  ),
  crossing(
    "falling-choir",
    "The Falling Choir",
    "spire",
    2,
    "hazard",
    "Bronze masks spill from a cracked ceiling. They strike the floor without a sound. One still holds the breath of the person who wore it.",
    [
      answer(
        "Shelter beneath the nearest arch",
        "Gain 6 resolve",
        "The rain of masks passes. You leave a candle in the arch for the people whose faces the metal kept.",
        { resolve: 6 },
      ),
      answer(
        "Catch the mask with the breath inside",
        "Lose 8 health · gain 35 gold",
        "Its edge cuts through a glove. The mask exhales once, and a silver keepsake falls from its sealed mouth.",
        { hp: -8, gold: 35 },
      ),
    ],
  ),
  crossing(
    "tide-lock",
    "The Tide's Arithmetic",
    "saltreach",
    4,
    "puzzle",
    "A harbor lock has three gauges: water, salt, and debt. The debt gauge rises when the others fall. A ferryman's chalk mark points to the overflow channel.",
    [
      answer(
        "Open the overflow before paying the lock",
        "Open a shortcut · gain 12 energy",
        "The lock drains into an abandoned canal. A towpath emerges beneath the salt, leading deeper into the harbor.",
        { shortcut: true, energy: 12 },
      ),
      answer(
        "Pay the lock's old toll",
        "Spend 12 gold · restore 20 health",
        "The gatekeeper accepts the coin and offers clean water from a bottle tied to the gauge.",
        { gold: -12, requiresGold: 12, hp: 20 },
      ),
    ],
  ),
  crossing(
    "dry-wave",
    "The Dry Wave",
    "saltreach",
    4,
    "hazard",
    "A wave of white salt moves between the ships. Its crest carries nails, rope, and the sound of a storm that happened before you were born.",
    [
      answer(
        "Tie yourself to a mooring ring",
        "Spend 6 energy · gain 10 resolve",
        "The rope holds. When the salt settles, you are still standing on the same side of the harbor.",
        { energy: -6, resolve: 10 },
      ),
      answer(
        "Climb into an overturned boat",
        "Lose 6 health · find 42 gold",
        "The boat rolls once and catches on a piling. Coins spill from a drawer beneath its broken seat.",
        { hp: -6, gold: 42 },
      ),
    ],
  ),
  crossing(
    "blank-shelf",
    "The Shelf Without a Title",
    "archive",
    5,
    "puzzle",
    "A locked shelf displays three books: an accusation, a defense, and an empty binding. The lock asks for the only account that has room for another witness.",
    [
      answer(
        "Place the empty binding on the reading desk",
        "Open a shortcut · gain 15 resolve",
        "New lines appear inside the binding. The shelf turns on a hinge, revealing the readers' passage behind it.",
        { shortcut: true, resolve: 15 },
      ),
      answer(
        "Copy the lock's question into your journal",
        "Gain 14 energy",
        "The lock recognizes a reader willing to keep a question. It releases its smallest latch.",
        { energy: 14 },
      ),
    ],
  ),
  crossing(
    "paper-fire",
    "A Fire Made of Margins",
    "archive",
    5,
    "hazard",
    "Loose pages burn in midair. The fire consumes every sentence except the notes written by someone who disagreed. The surviving scraps drift toward the stacks.",
    [
      answer(
        "Gather the surviving arguments",
        "Will 7 · gain 55 gold",
        "The scraps form a map of the fire's blind spots. A book rescuer pays for a copy.",
        { requiresAttribute: { id: "will", value: 7 }, gold: 55 },
      ),
      answer(
        "Close the brass shutters",
        "Spend 5 energy · restore 18 health",
        "The draft stops. You find an unburnt cot in the shadow of the shutter and rest there briefly.",
        { energy: -5, hp: 18 },
      ),
    ],
  ),
  crossing(
    "wrong-north",
    "A Compass Facing Inward",
    "observatory",
    6,
    "puzzle",
    "The observatory's compass points toward its own needle. Around it, eight mirror windows show the same star at eight different ages. The youngest sky is still incomplete.",
    [
      answer(
        "Open the window with an unfinished sky",
        "Open a shortcut · gain 12 resolve",
        "Fresh air enters a sealed corridor. The stars stop repeating, and a stair reveals its true direction.",
        { shortcut: true, resolve: 12 },
      ),
      answer(
        "Cover the compass with your cloak",
        "Gain 16 energy",
        "Without its reflection, the needle turns north. The nearest door follows it.",
        { energy: 16 },
      ),
    ],
  ),
  crossing(
    "glass-rain",
    "Weather from Another Life",
    "observatory",
    6,
    "hazard",
    "Rain falls upward through the dome. Each glass drop contains a day you might have lived. Breaking one would let the day go, along with whoever is waiting inside it.",
    [
      answer(
        "Let the impossible rain pass",
        "Gain 14 resolve",
        "You wait without reaching for another life. The drops climb into the sky and leave this one intact.",
        { resolve: 14 },
      ),
      answer(
        "Shelter the nearest drop in your palm",
        "Lose 9 health · restore 18 energy",
        "Cold glass bites through the glove. Inside it, someone lights a small lamp in gratitude.",
        { hp: -9, energy: 18 },
      ),
    ],
  ),
  crossing(
    "pearl-weight",
    "A Bridge of Unequal Memories",
    "rootsea",
    7,
    "puzzle",
    "Two bowls of pearls balance a bridge. One holds triumphs; the other holds ordinary days. The ordinary bowl is heavier, though it contains only a breakfast and a walk home.",
    [
      answer(
        "Place a quiet memory beside the breakfast",
        "Open a shortcut · restore 24 health",
        "The sea accepts a day without a victory in it. Roots lift a walkway from the water and hold it still.",
        { shortcut: true, hp: 24 },
      ),
      answer(
        "Ask the shore to hold the bridge a moment",
        "Gain 18 energy",
        "The roots remember your footsteps. They carry you across without asking you to leave a memory behind.",
        { energy: 18 },
      ),
    ],
  ),
  crossing(
    "shore-turns",
    "The Shore Turns in Its Sleep",
    "rootsea",
    7,
    "hazard",
    "The coast rolls over beneath the water. Trees drift upside down, their roots protecting windows full of yellow kitchen light. A whole village is dreaming under your boots.",
    [
      answer(
        "Walk where the roofs cast shadows",
        "Agility 7 · gain 65 gold",
        "You follow the village's old streets through their reflections. A brass street sign points you toward a lost supply chest.",
        { requiresAttribute: { id: "agility", value: 7 }, gold: 65 },
      ),
      answer(
        "Wait on a root until the village settles",
        "Restore 25 health · lose 4 energy",
        "Warm light shines through the water. For a little while, the village dreams of someone coming home.",
        { hp: 25, energy: -4 },
      ),
    ],
  ),
  crossing(
    "open-circle",
    "The Engine's Missing Spoke",
    "engine",
    8,
    "puzzle",
    "A wheel locks every time it completes a perfect turn. Someone removed one spoke long ago, then hid the gap behind a gold plate. The machine calls the gap a fault.",
    [
      answer(
        "Leave the missing spoke uncovered",
        "Open a shortcut · gain 20 resolve",
        "The imperfect wheel turns freely. The service gate opens for the first time since the first Dimming.",
        { shortcut: true, resolve: 20 },
      ),
      answer(
        "Turn the wheel by hand",
        "Spend 8 energy · restore 30 health",
        "You move it one patient turn at a time. A cooling vent opens, releasing warmth without fire.",
        { energy: -8, hp: 30 },
      ),
    ],
  ),
  crossing(
    "unspent-dawn",
    "A Pocket of Unspent Dawn",
    "engine",
    8,
    "hazard",
    "Morning pools beneath a cracked conduit. It is beautiful enough to make the room's missing details easy to overlook. A painted family has already lost one chair.",
    [
      answer(
        "Close the conduit before stepping through",
        "Might 8 · gain 80 gold",
        "The dawn retreats into its pipe. A maintenance chest becomes visible where the light had erased its outline.",
        { requiresAttribute: { id: "might", value: 8 }, gold: 80 },
      ),
      answer(
        "Shade the crossing with your lantern",
        "Spend 7 energy · gain 18 resolve",
        "Your small flame gives the light a boundary. You cross slowly, keeping every chair in the painted room.",
        { energy: -7, resolve: 18 },
      ),
    ],
  ),
];
